[package]
name = "eth1_test_rig"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["time"] }
ethers-core = { git = "https://github.com/gakonst/ethers-rs", rev = "89bc6420bbfdeb6ec891b0f701dd4768505f31c7" }
ethers-providers = { git = "https://github.com/gakonst/ethers-rs", rev = "89bc6420bbfdeb6ec891b0f701dd4768505f31c7" }
ethers-contract = { git = "https://github.com/gakonst/ethers-rs", rev = "89bc6420bbfdeb6ec891b0f701dd4768505f31c7" }
types = { path = "../../consensus/types"}
serde_json = "1.0.58"
deposit_contract = { path = "../../common/deposit_contract"}
unused_port = { path = "../../common/unused_port" }
